app.config(["$translateProvider", function($translateProvider) {

    $translateProvider.translations("nb_NO", {
      server: "Server feil",
      server0: "Skriv inn gammelt passord!",
      server1: "E-post er ikke gyldig!",
      server2: "Skriv inn navnet ditt!",
      server3: "Det gamle passordet er ikke gyldig!",
      server4: "Passored er ikke gyldig!",
      server5: "Denne eposten har allerede blitt registrert!",
      server6: "Skriv inn tittel!",
      server7: "Feil E-post og/ eller passord kombinasjon!",
      collection: "Samling",
      collectionNew: "Ny samling",
      collectionDeleteConfirm: "Slett samling?\nAlle bokmerker vil bli slettet!",
      saveChanges: "Lagre endringer",
      saveError: "Lagrings feil!",
      saveSuccess: "Lagret!",
      addSuccess: "Lagt til!",
      moveSuccess: "Flytter!",
      removeSuccess: "Fjernet!",
      coverUpload: "Last opp cover",
      fileUploadUnable: "Denne filen kan ikke lastes opp!",
      fileUploadError: "Filopplastnings feil. Vennligst prøv en annen fil!",
      linkNotRecognized: "Lenken er ikke gjenkjent",
      permalink: "Permalenke:",
      profile: "Profil",
      signIn: "Logg inn",
      myCollections: "Mine samlinger",
      save: "Lagre",
      remove: "Fjern",
      elements: "elementer",
      about: "Om",
      blog: "Blogg",
      tools: "Verktøy",
      signInSocial: "Logg inn med",
      signUpSocial: "Registrer deg med",
      signUp: "Registrer deg",
      register: "Registrer deg",
      recoverPassword: "Nullstill passord",
      password: "Passord",
      edit: "Rediger",
      editMin: "Rediger",
      collectionEmpty: "Samlingen er tom",
      fillItTwoWays: "To måter for å fylle opp samlingen",
      recommend: "Anbefal",
      installExtension: "Installer utvidelse",
      extensionDescription: "The most simple, easy and super fast way to keep \n important of the web. Den enkleste og super hurtige metoden for å holde styr \n på vikitge ting på internett",
      enterLink: "Skriv inn link",
      enterLinkDescription: "Skriv inn en link til ett nettsted \n artikkel, bilde eller video. Alt du vil ha.",
      backToCollection: "Tilbake til samling",
      viewOn: "Vis på",
      articled: "artikkel",
      imaged: "bilde",
      videod: "innhold",
      linkd: "link",
      article: "Artikkel",
      image: "Bilde",
      video: "Innhold",
      link: "Link",
      vkontakte: "Вконтакте",
      facebook: "Facebook",
      twitter: "Twitter",
      on: "på",
      basicData: "Konto innstillinger",
      yourName: "Ditt navn",
      changePassword: "Bytt passord",
      newPassword: "Nytt passord",
      currentPassword: "Gjeldende passord",
      findBookmarkLong: "Finn bokmerke med tittle, beskrivelse eller nettsted...",
      nothingFound: "Ingenting ble funnet",
      add: "Legg til",
      cancel: "Avbrut",
      covers: "Omslag",
      upload: "Last opp",
      imagesOnly: "Kun bilder. \n Maks størrelse: 5mb.",
      uploadProgress: "Laster opp...",
      fontFamily: "Font familie",
      fontSize: "Font størrelse",
      interfaceStyle: "Grensesnitt stil",
      additional: "Ekstra",
      fixedWidth: "Fast bredde",
      logOut: "Logg ut",
      titleAndDescription: "Tittle & beskrivelse",
      enterTitle: "Skriv inn tittel",
      enterDescription: "Skriv inn beskrivelse",
      enable: "Aktivert",
      type: "Type",
      publicCollection: "Offentlig samling",
      shareCollection: "Del samling",
      sendEmail: "Send epost",
      copyLink: "Kopier en link",
      language: "Språk",
      iHaveAccount: "Jeg har allerede en konto",
      createFirstCollection: "Lag den første samling",
      checkYourEmail: "Sjekk inboksen din!",
      und: "&",
      from: "fra",
      passwordChangeSuccess: "Passordet er endret!",
      smartSearch: "Smart søk",
      subscribe: "Følg",
      youSubscribed: "Følger",
      subscriptions: "Følger",
      subscriptionsCollection: "Følg samlinger",
      tags: "Tags",
      addTag: "Legg til en tag",
      noDescription: "Ingen beskrivelse",
      basic: "Enkel",
      background: "Bakgrunn",
      removeBackground: "Fjern bakgrunn",
      or: "eller",
      noCollections: "Ingen samlinger",
      noSubscriptions: "Ingen abonnementer",
      welcome: "Velkommen",
      toRefreshedRaindrop: "til Raindrop",
      comfortableReading: "Komfortabel lesing",
      publicCollections: "Offentlige samlinger",
      collectionsCount: "samlinger",
      noPublicCollections: "Ingen offentlige samlinger",
      noPublicCollectionsD: "Denne brukeren har ikke laget, eller har ingen offentlige samlinger.",
      all: "Alle",
      mobileApp: "Mobil App",
      exportBookmarks: "Eksporter bokmerker",

        cover: "Cover",
      saveToCollection: "Lagre til samlingen",
      selectCollection: "Velg samling",
      myAccount: "Min konto",
      enterTitleAndCollection: "Skriv in tittle og samling",
      selectPreferedType: "Velg foretrukket type",
      back: "Tilbake",
      bySort: "Sortert",
      byName: "Etter navn",
      byDate: "Etter dato",
      findOrCreateCollection: "Finn eller lag en ny samling",
      createCollection: "Ny samling",
      startToSave: "Vennligst logg inn for å starte!",
      checkAgain: "Sjekk på nytt!",
      clickToMakeScreenshot: "Klikk for å ta ett skjermbilde"
    });

    $translateProvider.translations("en_US", {
      server: "Server error",
      server0: "Enter old password!",
      server1: "E-mail is not valid!",
      server2: "Enter your name!",
      server3: "Old password is not valid!",
      server4: "Password is not valid!",
      server5: "This email is already registered!",
      server6: "Enter title!",
      server7: "Wrong E-mail and/or password combination!",
      collection: "Collection",
      collectionNew: "New Collection",
      collectionDeleteConfirm: "Delete collection?\nAll bookmarks will be deleted!",
      saveChanges: "Save changes",
      saveError: "Save error!",
      saveSuccess: "Successfully saved!",
      addSuccess: "Successfully added!",
      moveSuccess: "Successfully moved!",
      removeSuccess: "Successfully removed!",
      coverUpload: "Cover upload",
      fileUploadUnable: "This file can not be uploaded!",
      fileUploadError: "File upload error. Try another file!",
      linkNotRecognized: "Link is not recognized",
      permalink: "Permalink:",
      profile: "Profile",
      signIn: "Log in",
      myCollections: "My collections",
      save: "Save",
      remove: "Remove",
      elements: "elements",
      about: "About",
      blog: "Blog",
      tools: "Tools",
      signInSocial: "Log in with",
      signUpSocial: "Sign up with",
      signUp: "Sign up",
      register: "Sign up",
      recoverPassword: "Reset password",
      password: "Password",
      edit: "Edit",
      editMin: "Edit",
      collectionEmpty: "Collection is empty",
      fillItTwoWays: "The two ways to fill collection",
      recommend: "Recommend",
      installExtension: "Install extension",
      extensionDescription: "The most simple, easy and super fast way to keep \n important of the web.",
      enterLink: "Enter link",
      enterLinkDescription: "Enter a link to any web page,\n article, photo or video. Anything you want.",
      backToCollection: "Back to collection",
      viewOn: "View on",
      articled: "article",
      imaged: "photo",
      videod: "content",
      linkd: "link",
      article: "Article",
      image: "Photo",
      video: "Content",
      link: "Link",
      vkontakte: "Вконтакте",
      facebook: "Facebook",
      twitter: "Twitter",
      on: "on",
      basicData: "Account settings",
      yourName: "Your name",
      changePassword: "Change password",
      newPassword: "New password",
      currentPassword: "Current password",
      findBookmarkLong: "Find bookmark by title, description or website...",
      nothingFound: "Nothing found",
      add: "Add",
      cancel: "Cancel",
      covers: "Covers",
      upload: "Upload",
      imagesOnly: "Images only. \n Max size: 5mb.",
      uploadProgress: "Uploading...",
      fontFamily: "Font family",
      fontSize: "Font size",
      interfaceStyle: "Interface style",
      additional: "Additional",
      fixedWidth: "Fixed width",
      logOut: "Logout",
      titleAndDescription: "Title & description",
      enterTitle: "Enter title",
      enterDescription: "Enter description",
      enable: "Enabled",
      type: "Type",
      publicCollection: "Public collection",
      shareCollection: "Share collection",
      sendEmail: "Send email",
      copyLink: "Copy a link",
      language: "Language",
      iHaveAccount: "I have account already",
      createFirstCollection: "Create first collection",
      checkYourEmail: "Check your inbox!",
      und: "&",
      from: "from",
      passwordChangeSuccess: "Password successfully changed!",
      smartSearch: "Smart search",
      subscribe: "Follow",
      youSubscribed: "Following",
      subscriptions: "Following",
      subscriptionsCollection: "Follow collections",
      tags: "Tags",
      addTag: "Add a tag",
      noDescription: "No description",
      basic: "Basic",
      background: "Background",
      removeBackground: "Remove background",
      or: "or",
      noCollections: "No collections",
      noSubscriptions: "No subscriptions",
      welcome: "Welcome",
      toRefreshedRaindrop: "to Raindrop",
      comfortableReading: "Comfortable reading",
      publicCollections: "Public collections",
      collectionsCount: "collections",
      noPublicCollections: "No public collections",
      noPublicCollectionsD: "This user has not created or does not have any public collection.",
      all: "All",
      mobileApp: "Mobile App",
      exportBookmarks: "Export bookmarks",

        cover: "Cover",
	    saveToCollection: "Save to collection",
	    selectCollection: "Select Collection",
	    myAccount: "My account",
	    enterTitleAndCollection: "Enter title and collection",
	    selectPreferedType: "Select prefered type",
	    back: "Back",
	    byName: "By name",
	    byDate: "By date",
	    findOrCreateCollection: "Find or create new collection",
	    createCollection: "New collection",
	    startToSave: "Please, log in to start!",
	    checkAgain: "Check again!",
	    clickToMakeScreenshot: "Click to make screenshot"
    });

  $translateProvider.translations("ru_RU", {
    server: "Неизвестная ошибка",
    server0: "Укажите старый пароль!",
    server1: "E-mail введен не верно!",
    server2: "Укажите пожалуйста ваше имя",
    server3: "Ваш старый пароль указан не верно!",
    server4: "Пароль указан не верно!",
    server5: "Данный e-mail уже используется!",
    server6: "Название/заголовок не указано!",
    server7: "Пользователь с таким e-mail не найден!",
    collection: "Коллекция",
    collectionNew: "Новая коллекция",
    collectionDeleteConfirm: "Действительно удалить коллекцию?\nВсе закладки внутри коллекции будут также удалены!",
    saveChanges: "Сохранить изменения",
    saveError: "Произошла ошибка при сохранение!",
    saveSuccess: "Успешно сохранен!",
    addSuccess: "Успешно добавлен!",
    moveSuccess: "Успешно перемещен!",
    removeSuccess: "Успешно удален!",
    coverUpload: "Загрузка обложки",
    fileUploadUnable: "Данный файл невозможно загрузить!",
    fileUploadError: "Произошла ошибка при загрузке файла. Попробуйте другой файл!",
    linkNotRecognized: "Ссылка не распознана",
    permalink: "Постоянная ссылка на коллекцию:",
    profile: "Профиль",
    signIn: "Войти",
    myCollections: "Мои коллекции",
    save: "Сохранить",
    remove: "Удалить",
    elements: "елемента",
    about: "О проекте",
    blog: "Блог",
    tools: "Инструменты",
    signInSocial: "Войти через социальную сеть",
    signUpSocial: "Зарегистрироваться через социальную сеть",
    signUp: "Регистрация",
    register: "Зарегистрироваться",
    recoverPassword: "Восстановить пароль",
    password: "Пароль",
    edit: "Редактировать",
    editMin: "Ред",
    collectionEmpty: "Коллекция пуста",
    fillItTwoWays: "Заполнить ее можно двумя способами",
    recommend: "Рекомендуем",
    installExtension: "Установить расширение",
    extensionDescription: "Самый простой, удобный и супер быстрый\nспособ сохранить важное из интернета.",
    enterLink: "Указать ссылку",
    enterLinkDescription: "Укажите ссылку на любую\nстраницу, статью, фото или видео.",
    backToCollection: "В коллекцию",
    viewOn: "Смотреть на",
    articled: "статью",
    imaged: "фото",
    videod: "контент",
    linkd: "ссылку",
    article: "Статья",
    image: "Фото",
    video: "Контент",
    link: "Ссылка",
    vkontakte: "Вконтакте",
    facebook: "Facebook",
    twitter: "Twitter",
    on: "на",
    basicData: "Основные данные",
    yourName: "Ваше имя",
    changePassword: "Сменить пароль",
    newPassword: "Новый пароль",
    currentPassword: "Текущий пароль",
    findBookmarkLong: "Найти закладку по заголовку, описанию или сайту...",
    nothingFound: "Ничего не найдено",
    add: "Добавить",
    cancel: "Отмена",
    covers: "Обложки",
    upload: "Загрузить",
    imagesOnly: "Картинка не более 5 мб.",
    uploadProgress: "Идет загрузка...",
    fontFamily: "Семейство шрифта",
    fontSize: "Размер шрифта",
    interfaceStyle: "Стиль интерфейса",
    additional: "Дополнительно",
    fixedWidth: "Фиксированная ширина",
    logOut: "Выйти",
    titleAndDescription: "Заголовок и описание",
    enterTitle: "Введите заголовок",
    enterDescription: "Введите описание",
    enable: "Вкл.",
    type: "Тип",
    publicCollection: "Публичная коллекция",
    shareCollection: "Поделиться коллекцией",
    sendEmail: "Отправить по почте",
    copyLink: "Скопировать ссылку",
    language: "Язык",
    iHaveAccount: "У меня уже есть аккаунт",
    createFirstCollection: "Создать первую коллекцию",
    checkYourEmail: "Проверьте ваш почтовый ящик!",
    und: "и",
    from: "от",
    passwordChangeSuccess: "Пароль успешно изменен!",
    smartSearch: "Умный поиск",
    subscribe: "Подписаться",
    youSubscribed: "Вы подписаны!",
    subscriptions: "Подписки",
    subscriptionsCollection: "Подписки",
    tags: "Теги",
    addTag: "Добавить тег",
    noDescription: "Нет описания",
    basic: "Основное",
    background: "Фон",
    removeBackground: "Удалить фон",
    or: "или",
    noCollections: "Нет коллекций",
    noSubscriptions: "Нет подписок",
    welcome: "Добро пожаловать",
    toRefreshedRaindrop: "В обновленный Raindrop",
    comfortableReading: "Комфортное чтение",
    publicCollections: "Публичные коллекции",
    collectionsCount: "коллекций",
    noPublicCollections: "Нет публичных коллекций",
    noPublicCollectionsD: "Пользователь еще не создал либо не имеет публичных коллекции.",
    all: "Все",
    mobileApp: "Мобильное приложение",
    exportBookmarks: "Экспорт закладок",

    cover: "Обложка",
    saveToCollection: "Сохранить в коллекцию",
    selectCollection: "Выбрать коллекцию",
    myAccount: "Мой аккаунт",
    enterTitleAndCollection: "Укажите заголовок и коллекцию",
    selectPreferedType: "Выберите подходящий тип страницы",
    back: "Назад",
    byName: "По имени",
    byDate: "По дате",
    findOrCreateCollection: "Найти или создать коллекцию",
    createCollection: "Создать коллекцию",
    startToSave: "Пожалуйста, войдите, чтобы начать сохранять закладки",
    checkAgain: "Проверить еще раз!",
    clickToMakeScreenshot: "Нажмите, чтобы создать скриншот"
  });

	
	//language
	var lang = (navigator.language || navigator.systemLanguage || navigator.userLanguage || 'en').substr(0, 2).toLowerCase();
	if ((lang == "ru") || (lang == "ru_RU"))
    lang = 'ru_RU';
  else if ((lang == "no") || (lang == "nb_NO" || (lang == "no_NO")))
    lang = 'nb_NO';
  else
    lang = 'en_US';
	$translateProvider.preferredLanguage(lang);
}
]);
